# -*- coding: utf-8 -*-
"""reducao_ALUNO_2EF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doo_ki7Is4wwsztfL9c4zzN0Omu9eOdD
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

chunksize = 100000  # lê 100 mil linhas por vez
amostra = []

# lê o arquivo em partes, sorteando um pedacinho de cada
for chunk in pd.read_csv("TS_ALUNO_2EF.csv", chunksize=chunksize, encoding="latin-1", sep=";"):
    frac = 10000 / len(chunk)  # fração proporcional para depois juntar
    if frac < 1:  # só sorteia se for menor que 100%
        amostra.append(chunk.sample(frac=frac, random_state=42))
    else:
        amostra.append(chunk)

# junta as amostras e pega exatamente 10.000
df_reduzido = pd.concat(amostra).sample(n=10000, random_state=42)

# salva no CSV final
df_reduzido.to_csv("MICRODADOS_SAEB_2023_ALUNO_2EF.csv", index=False, encoding="utf-8")

#from google.colab import drive
#drive.mount('/content/drive')

# salva dentro da pasta principal do Drive
df_reduzido.to_csv("results/MICRODADOS_SAEB_2023_ALUNO_2EF.csv", index=False, encoding="utf-8")