# -*- coding: utf-8 -*-
"""SAEB_escola_tratado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVMuZeqzvSqjvaZ83rlm2hCrPbWwXsSd
"""

#Bibliotecas

import pandas as pd
import numpy as np
from IPython.display import display

# Montar o Google Drive no Colab
#from google.colab import drive
#drive.mount('/content/drive')

# Caminho do arquivo no Google Drive
caminho = "data/SAEB_2023_escola.csv"

# Lê a base original
df = pd.read_csv(caminho, sep=",", encoding="utf-8")

#Verificar as colunas e primeiro 5 linhas

df.head()

# Selecionar apenas as colunas relevantes
colunas_saeb = [
    # Identificação geográfica
    "ID_REGIAO", "ID_UF", "ID_MUNICIPIO",

    # Identificação da escola
    "ID_ESCOLA", "IN_PUBLICA", "ID_LOCALIZACAO",

    # Formação docente
    "PC_FORMACAO_DOCENTE_INICIAL", "PC_FORMACAO_DOCENTE_FINAL",

    # Médias de desempenho
    "MEDIA_5EF_LP", "MEDIA_5EF_MT",
    "MEDIA_9EF_LP", "MEDIA_9EF_MT",
    "MEDIA_EMT_LP", "MEDIA_EMT_MT",
    "MEDIA_EMI_LP", "MEDIA_EMI_MT",
    "MEDIA_EM_LP", "MEDIA_EM_MT"
]

# Criar reduzido
if 'df_saeb_reduzido' not in globals():
    df_saeb_reduzido = df[colunas_saeb].copy()
else:
    # garante que contém as colunas desejadas
    df_saeb_reduzido = df_saeb_reduzido.reindex(columns=colunas_saeb)

# Visão geral
print("Dimensão (linhas, colunas):", df_saeb_reduzido.shape)
display(df_saeb_reduzido.head(6))

# Tipos de dados e nulos (apenas nas colunas que escolhemos)
print("\nDtypes:")
print(df_saeb_reduzido.dtypes)

print("\nNulos por coluna (ordenado desc):")
display(df_saeb_reduzido.isnull().sum().sort_values(ascending=False))

# Converter possíveis strings com vírgula decimal para ponto e forçar numérico nas colunas percentuais e de média
percent_cols = ["PC_FORMACAO_DOCENTE_INICIAL", "PC_FORMACAO_DOCENTE_FINAL"]
media_cols = [
    "MEDIA_5EF_LP","MEDIA_5EF_MT","MEDIA_9EF_LP","MEDIA_9EF_MT",
    "MEDIA_EMT_LP","MEDIA_EMT_MT","MEDIA_EMI_LP","MEDIA_EMI_MT",
    "MEDIA_EM_LP","MEDIA_EM_MT"
]

for c in percent_cols + media_cols:
    if c in df_saeb_reduzido.columns:
        df_saeb_reduzido[c] = pd.to_numeric(df_saeb_reduzido[c].astype(str).str.replace(",",".").str.strip(), errors='coerce')

print("\nDtypes pós conversão (percentuais e médias):")
print(df_saeb_reduzido[percent_cols + media_cols].dtypes)

# Estatísticas resumidas das médias
print("\nResumo estatístico das médias (MEDIA_*):")
display(df_saeb_reduzido[media_cols].describe())

# Verificar valores fora do intervalo esperado
print("\n--- Checagem de intervalos ---")

# Percentuais (esperado: 0–100)
for c in ["PC_FORMACAO_DOCENTE_INICIAL", "PC_FORMACAO_DOCENTE_FINAL"]:
    if c in df_saeb_reduzido:
        inv = df_saeb_reduzido[(df_saeb_reduzido[c].notna()) &
                               ((df_saeb_reduzido[c] < 0) | (df_saeb_reduzido[c] > 100))]
        print(f"{c}: {len(inv)} inválidos (esperado 0–100)")
        if len(inv) > 0:
            display(inv.head(5))

# Médias SAEB (esperado: 0–500)
for c in [
    "MEDIA_5EF_LP", "MEDIA_5EF_MT",
    "MEDIA_9EF_LP", "MEDIA_9EF_MT",
    "MEDIA_EMT_LP", "MEDIA_EMT_MT",
    "MEDIA_EMI_LP", "MEDIA_EMI_MT",
    "MEDIA_EM_LP", "MEDIA_EM_MT"
]:
    if c in df_saeb_reduzido:
        inv = df_saeb_reduzido[(df_saeb_reduzido[c].notna()) &
                               ((df_saeb_reduzido[c] < 0) | (df_saeb_reduzido[c] > 500))]
        print(f"{c}: {len(inv)} inválidos (esperado 0–500)")
        if len(inv) > 0:
            display(inv.head(5))

# Duplicatas por ID_ESCOLA
if "ID_ESCOLA" in df_saeb_reduzido.columns:
    dup_count = df_saeb_reduzido.duplicated(subset=["ID_ESCOLA"]).sum()
    print("\nNúmero de duplicatas (ID_ESCOLA):", dup_count)
    if dup_count>0:
        display(df_saeb_reduzido[df_saeb_reduzido.duplicated(subset=["ID_ESCOLA"], keep=False)].head(8))

print("Valores únicos IN_PUBLICA:", df_saeb_reduzido["IN_PUBLICA"].unique())
print("Valores únicos ID_LOCALIZACAO:", df_saeb_reduzido["ID_LOCALIZACAO"].unique())

"""# LIMPEZA BÁSICA"""

# Remover espaços em colunas de identificação textual (se existirem)
if "IN_PUBLICA" in df_saeb_reduzido.columns:
    df_saeb_reduzido["IN_PUBLICA"] = df_saeb_reduzido["IN_PUBLICA"].astype(str).str.strip()

if "ID_LOCALIZACAO" in df_saeb_reduzido.columns:
    df_saeb_reduzido["ID_LOCALIZACAO"] = df_saeb_reduzido["ID_LOCALIZACAO"].astype(str).str.strip()

#Normalizar tipos categóricos
df_saeb_reduzido["IN_PUBLICA"] = df_saeb_reduzido["IN_PUBLICA"].astype("category")
df_saeb_reduzido["ID_LOCALIZACAO"] = df_saeb_reduzido["ID_LOCALIZACAO"].astype("category")

# Criar flags de missing (útil para análises posteriores)
for c in percent_cols + media_cols:
    if c in df_saeb_reduzido.columns:
        df_saeb_reduzido[f"{c}_missing"] = df_saeb_reduzido[c].isnull().astype(int)

#  Opção conservadora: NÃO imputar médias/percentuais — mantém NaN
#    Mantemos os dados numéricos prontos e com tipos float
df_saeb_reduzido[percent_cols + media_cols] = df_saeb_reduzido[percent_cols + media_cols].astype(float)

#  Verificar resultado final (nulos resumido)
print("Nulos por coluna (após limpeza básica):")
display(df_saeb_reduzido.isnull().sum().sort_values(ascending=False).head(30))

# Salvar versão reduzida/limpa no Drive
df_saeb_reduzido.to_csv('results/SAEB_escola_tratado.csv', index=False)

"""Primeiro, montamos o Google Drive no Colab e carregamos o arquivo CSV da base SAEB (escola). Selecionamos apenas as colunas relevantes para a análise, que incluem identificação geográfica, dados da escola, formação docente e médias de desempenho. Criamos um DataFrame reduzido contendo apenas essas colunas, garantindo uma base mais enxuta e organizada.

Em seguida, realizamos a conversão de tipos, transformando valores que poderiam estar como strings com vírgula decimal em números do tipo float, para que os percentuais e as médias pudessem ser corretamente interpretados e utilizados em análises. Após isso, verificamos se os valores das colunas percentuais estavam entre 0 e 100 e se os valores das médias SAEB estavam entre 0 e 500. Não foram encontrados valores fora desses intervalos, o que indica que os dados estavam consistentes após a conversão.

Também verificamos duplicatas utilizando o identificador de escola (ID_ESCOLA) e constatamos que não havia registros duplicados, garantindo que cada escola estava representada apenas uma vez. As colunas categóricas foram padronizadas: a coluna IN_PUBLICA mostrou que todas as escolas eram públicas.

Para os valores faltantes (NaN), criamos flags específicas indicando quais registros estavam ausentes em cada coluna de percentuais e médias. Optou-se por não imputar valores nesse momento, mantendo os NaNs para análises futuras, garantindo que a ausência de dados pudesse ser monitorada.

Por fim, exportamos a versão tratada da base para o Google Drive, resultando em uma tabela limpa, com tipos consistentes, categorias padronizadas, sem duplicatas e com os missing controlados. Esta versão está pronta para ser cruzada com outras bases de alunos ou professores e para análises voltadas à identificação de padrões no perfil de estudantes com TEA e TDAH.
"""