# -*- coding: utf-8 -*-
"""SAEB_ALUNO_34EM_tratado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgNmOOfaydBicItqGA1IqKX4AY-RSds8
"""

#Bibliotecas

import pandas as pd
import numpy as np
from IPython.display import display

# Montar o Google Drive no Colab
#from google.colab import drive
#drive.mount('/content/drive')

# Caminho do arquivo no Google Drive
CAMINHO_ENTRADA = "data/SAEB_ALUNO_34EM.csv"

# Lê a base original
df = pd.read_csv(CAMINHO_ENTRADA, sep=",", encoding="utf-8")

CAMINHO_SAIDA = "results/SAEB_34EM__tratado.csv"

# --- LISTA PADRONIZADA DE COLUNAS (Fim em Q20) ---
# Usamos o mesmo filtro dos outros anos.
COLUNAS_MANTER_FINAL = [
    # IDENTIFICADORES E PESOS (Para Merge e Amostragem)
    'ID_ESCOLA', 'ID_ALUNO', 'ID_MUNICIPIO', 'ID_SERIE', 'ESTRATO',
    'PESO_ALUNO_LP', 'PESO_ALUNO_MT', 'PESO_ALUNO_INSE',

    # RESULTADO E CONTEXTO EDUCACIONAL
    'PROFICIENCIA_LP', 'ERRO_PADRAO_LP', 'PROFICIENCIA_MT', 'ERRO_PADRAO_MT',
    'PROFICIENCIA_LP_SAEB', 'ERRO_PADRAO_LP_SAEB', 'PROFICIENCIA_MT_SAEB', 'ERRO_PADRAO_MT_SAEB',
    'INSE_ALUNO', 'NU_TIPO_NIVEL_INSE', 'IN_PUBLICA', 'ID_LOCALIZACAO',

    # VARIÁVEIS CHAVE DO QUESTIONÁRIO (Até Q20, para padronizar com EF)
    'TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q03', 'TX_RESP_Q04', 'TX_RESP_Q05a',
    'TX_RESP_Q05b', 'TX_RESP_Q05c', 'TX_RESP_Q06', 'TX_RESP_Q07a', 'TX_RESP_Q07b',
    'TX_RESP_Q07c', 'TX_RESP_Q07d', 'TX_RESP_Q07e', 'TX_RESP_Q08', 'TX_RESP_Q09',
    'TX_RESP_Q10a', 'TX_RESP_Q10b', 'TX_RESP_Q10c', 'TX_RESP_Q10d', 'TX_RESP_Q10e',
    'TX_RESP_Q10f', 'TX_RESP_Q11a', 'TX_RESP_Q11b', 'TX_RESP_Q11c', 'TX_RESP_Q12a',
    'TX_RESP_Q12b', 'TX_RESP_Q12c', 'TX_RESP_Q12d', 'TX_RESP_Q12e', 'TX_RESP_Q12f',
    'TX_RESP_Q12g', 'TX_RESP_Q13a', 'TX_RESP_Q13b', 'TX_RESP_Q13c', 'TX_RESP_Q13d',
    'TX_RESP_Q13e', 'TX_RESP_Q13f', 'TX_RESP_Q13g', 'TX_RESP_Q13h', 'TX_RESP_Q13i',
    'TX_RESP_Q14', 'TX_RESP_Q15a', 'TX_RESP_Q15b', 'TX_RESP_Q16', 'TX_RESP_Q17',
    'TX_RESP_Q18', 'TX_RESP_Q19', 'TX_RESP_Q20'
]

"""**PROCESSO DE FILTRAGEM **"""

print(f"Iniciando filtragem final do {CAMINHO_ENTRADA}...")

try:
    # 2. Leitura do arquivo JÁ LIMPO
    # Não precisamos de tratamento de NaNs ou tipos, pois isso já foi feito.
    df = pd.read_csv(CAMINHO_ENTRADA, sep=',')

    # 3. Seleção e Filtro das Colunas
    # Usa df.filter para manter APENAS as colunas que estão na nossa lista padrão.
    df_filtrado = df.filter(items=COLUNAS_MANTER_FINAL)

    colunas_removidas = df.shape[1] - df_filtrado.shape[1]

    print(f"Colunas filtradas com sucesso. Foram removidas {colunas_removidas} colunas (ruído).")
    print(f"Base final com {df_filtrado.shape[0]} registros e {df_filtrado.shape[1]} colunas.")

    # 4. Salvar o arquivo final e padronizado
    df_filtrado.to_csv(CAMINHO_SAIDA, index=False)
    print(f"\n SUCESSO TOTAL: Ensino Médio padronizado e salvo em: {CAMINHO_SAIDA}")

except FileNotFoundError:
    print(f" ERRO: Verifique se o arquivo '{CAMINHO_ENTRADA}' está no local especificado.")
except Exception as e:
    print(f"\n ERRO FATAL: {e}")